service: shopping-list-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: ap-south-1

functions:
  echo:
    handler: src/index.handler
    events:
      - http:
          path: /echo
          method: post
