service: shopping-list-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: prod
  region: ap-south-1
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
    REGION: ${aws:region}
  http:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  health:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: get
   list:
    handler: src/list.handler
    events:
      - http:
          path: /list
          method: get
  create:
    handler: src/create.handler
    events:
      - http:
          path: /create
          method: post
 

resources:
  Resources:
    ShoppingListDynamoDBTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: _id
            AttributeType: S
          - AttributeName: itemName
            AttributeType: S
        KeySchema:
          - AttributeName: _id
            KeyType: HASH
          - AttributeName: itemName
            KeyType: RANGE

        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
